<script type="text/javascript">
    var latkeConfig = {
      "staticServePath": "${staticServePath}",
      "servePath": "${servePath}"
    };
    
    var qiniu = {
        "qiniuUploadToken": "${qiniuUploadToken}",
        "qiniuDomain": "${qiniuDomain}"
    };
    
    var Label = {
        "skinDirName": "${skinDirName}",
        "editorType": "${editorType}",
        "userRole": "${userRole}",
        "PAGE_SIZE": "${articleListDisplayCount}",
        "WINDOW_SIZE": "${articleListPaginationWindowSize}",
        "localeString": "${localeString}",
        "version": "${version}",
        "miniPostfix": "${miniPostfix}",
        "reportIssueLabel": "please report this issue on https://github.com/b3log/solo/issues/new",
        "noDataLabel": "${noDataLabel}",
        "linkDescriptionLabel": "${linkDescriptionLabel}",
        "addressInvalidLabel": "${addressInvalidLabel}",
        "selectLabel": "${selectLabel}",
        "outOfDateLabel":　"${outOfDateLabel}",
        "upToDateLabel": "${upToDateLabel}",
        "commentContentLabel": "${commentContentLabel}",
        "loadingLabel": "${loadingLabel}",
        "noCommentLabel": "${noCommentLabel}",
        "confirmRemoveLabel": "${confirmRemoveLabel}",
        "removeLabel": "${removeLabel}",
        "cancelPutTopLabel": "${cancelPutTopLabel}",
        "putTopLabel": "${putTopLabel}",
        "viewLabel": "${viewLabel}",
        "updateLabel": "${updateLabel}",
        "commentLabel": "${commentLabel}",
        "titleLabel": "${titleLabel}",
        "tagsLabel": "${tagsLabel}",
        "authorLabel": "${authorLabel}",
        "createDateLabel": "${createDateLabel}",
        "previousPageLabel": "${previousPageLabel}",
        "pageLabel": "${pageLabel}",
        "nextPagePabel": "${nextPagePabel}",
        "gotoLabel": "${gotoLabel}",
        "fileNameLabel": "${fileNameLabel}",
        "uploadDateLabel": "${uploadDateLabel}",
        "sizeLabel": "${sizeLabel}",
        "downloadCountLabel": "${downloadCountLabel}",
        "downloadLabel": "${downloadLabel}",
        "permalinkLabel": "${permalinkLabel}",
        "titleEmptyLabel": "${titleEmptyLabel}",
        "contentEmptyLabel": "${contentEmptyLabel}",
        "linkTitleLabel": "${linkTitleLabel}",
        "urlLabel": "${urlLabel}",
        "addressEmptyLabel": "${addressEmptyLabel}",
        "pluginNameLabel": "${pluginNameLabel}",
        "statusLabel": "${statusLabel}",
        "versionLabel": "${versionLabel}",
        "commentNameLabel": "${commentNameLabel}",
        "commentEmailLabel": "${commentEmailLabel}",
        "roleLabel": "${roleLabel}", 
        "administratorLabel": "${administratorLabel}",
        "duplicatedEmailLabel": "${duplicatedEmailLabel}",
        "mailInvalidLabel": "${mailInvalidLabel}",
        "mailCannotEmptyLabel": "${mailCannotEmptyLabel}",
        "noSettingLabel": "${noSettingLabel}",
        "blogEmptyLabel": "${blogEmptyLabel}",
        "sumLabel": "${sumLabel}",
        "countLabel": "${countLabel}",
        "blogArticleEmptyLabel": "${blogArticleEmptyLabel}",
        "importSuccLabel": "${importSuccLabel}",
        "categoryLabel": "${categoryLabel}",
        "importedLabel": "${importedLabel}",
        "passwordEmptyLabel": "${passwordEmptyLabel}",
        "tagsEmptyLabel": "${tagsEmptyLabel}",
        "abstractEmptyLabel": "${abstractEmptyLabel}",
        "commonUserLabel": "${commonUserLabel}",
        "articleLabel": "${articleLabel}",
        "enabledLabel": "${enabledLabel}",
        "disabledLabel": "${disabledLabel}",
        "signIsNullLabel": "${signIsNullLabel}",
        "editorLeaveLabel": "${editorLeaveLabel}",
        "editorPostLabel": "${editorPostLabel}",
        "enableLabel": "${enableLabel}",
        "disableLabel": "${disableLabel}",
        "settingLabel": "${settingLabel}",
        "linkEmptyLabel": "${linkEmptyLabel}",
        "openMethodLabel": "${openMethodLabel}",
        "typeLabel": "${typeLabel}",
        "markdownHelpLabel": "${markdownHelpLabel}",
        "notFoundLabel": "${notFoundLabel}",
        "em00Label": "${em00Label}",
        "em01Label": "${em01Label}",
        "em02Label": "${em02Label}",
        "em03Label": "${em03Label}",
        "em04Label": "${em04Label}",
        "em05Label": "${em05Label}",
        "em06Label": "${em06Label}",
        "em07Label": "${em07Label}",
        "em08Label": "${em08Label}",
        "em09Label": "${em09Label}",
        "em10Label": "${em10Label}",
        "em11Label": "${em11Label}",
        "em12Label": "${em12Label}",
        "em13Label": "${em13Label}",
        "em14Label": "${em14Label}",
        "paramSettingsLabel": "${paramSettingsLabel}",
        "nonNegativeIntegerOnlyLabel": "${nonNegativeIntegerOnlyLabel}",
        "indexTagDisplayCntLabel": "${indexTagDisplayCntLabel}",
        "indexRecentCommentDisplayCntLabel": "${indexRecentCommentDisplayCntLabel}",
        "indexMostCommentArticleDisplayCntLabel": "${indexMostCommentArticleDisplayCntLabel}",
        "indexMostViewArticleDisplayCntLabel": "${indexMostViewArticleDisplayCntLabel}",
        "pageSizeLabel": "${pageSizeLabel}",
        "windowSizeLabel": "${windowSizeLabel}",
        "randomArticlesDisplayCntLabel": "${randomArticlesDisplayCntLabel}",
        "relevantArticlesDisplayCntLabel": "${relevantArticlesDisplayCntLabel}",
        "externalRelevantArticlesDisplayCntLabel": "${externalRelevantArticlesDisplayCntLabel}",
        "nameTooLongLabel": "${nameTooLongLabel}",
        "navLabel": "${navLabel}",
        "userLabel": "${userLabel}",
        "changeRoleLabel": "${changeRoleLabel}",
        "visitorUserLabel": "${visitorUserLabel}",
        "autoSaveLabel": "${autoSaveLabel}"
    };    
    
    admin.init();
</script>